<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class FichaVehiculoEvaluacion extends Model
{
    use HasFactory;

    protected $table = 'ficha_vehiculo_evaluacion';

    public $timestamps = false;

    protected $fillable = [
        'ficha_vehiculo_id',
        'FECHA_REVISION',
        'NUMERO_REVISION',
        // FRENO DE SERVICIO
        'FS_EJE1_PESO', 'FS_EJE1_FUERZA_DER', 'FS_EJE1_FUERZA_IZQ', 'FS_EJE1_DESEQUILIBRIO',
        'FS_EJE2_PESO', 'FS_EJE2_FUERZA_DER', 'FS_EJE2_FUERZA_IZQ', 'FS_EJE2_DESEQUILIBRIO',
        'FS_EJE3_PESO', 'FS_EJE3_FUERZA_DER', 'FS_EJE3_FUERZA_IZQ', 'FS_EJE3_DESEQUILIBRIO',
        'FS_EJE4_PESO', 'FS_EJE4_FUERZA_DER', 'FS_EJE4_FUERZA_IZQ', 'FS_EJE4_DESEQUILIBRIO',
        'FS_EJE5_PESO', 'FS_EJE5_FUERZA_DER', 'FS_EJE5_FUERZA_IZQ', 'FS_EJE5_DESEQUILIBRIO',
        'FS_EFICIENCIA_TOTAL', 'FS_RESULTADO',
        // FRENO DE ESTACIONAMIENTO
        'FE_EJE1_PESO', 'FE_EJE1_FUERZA_DER', 'FE_EJE1_FUERZA_IZQ',
        'FE_EJE2_PESO', 'FE_EJE2_FUERZA_DER', 'FE_EJE2_FUERZA_IZQ',
        'FE_EJE3_PESO', 'FE_EJE3_FUERZA_DER', 'FE_EJE3_FUERZA_IZQ',
        'FE_EJE4_PESO', 'FE_EJE4_FUERZA_DER', 'FE_EJE4_FUERZA_IZQ',
        'FE_EJE5_PESO', 'FE_EJE5_FUERZA_DER', 'FE_EJE5_FUERZA_IZQ',
        'FE_EFICIENCIA_TOTAL', 'FE_RESULTADO',
        // FRENO DE EMERGENCIA
        'FEM_EJE1_PESO', 'FEM_EJE1_FUERZA_DER', 'FEM_EJE1_FUERZA_IZQ', 'FEM_EJE1_EFICIENCIA',
        'FEM_EJE2_PESO', 'FEM_EJE2_FUERZA_DER', 'FEM_EJE2_FUERZA_IZQ',
        'FEM_EJE3_PESO', 'FEM_EJE3_FUERZA_DER', 'FEM_EJE3_FUERZA_IZQ',
        'FEM_EJE4_PESO', 'FEM_EJE4_FUERZA_DER', 'FEM_EJE4_FUERZA_IZQ',
        'FEM_EJE5_PESO', 'FEM_EJE5_FUERZA_DER', 'FEM_EJE5_FUERZA_IZQ',
        'FEM_EJE1_DESEQUILIBRIO', 'FEM_EJE2_DESEQUILIBRIO', 'FEM_EJE3_DESEQUILIBRIO', 'FEM_EJE4_DESEQUILIBRIO', 'FEM_EJE5_DESEQUILIBRIO',
        'FEM_EFICIENCIA_TOTAL', 'FEM_RESULTADO',
        // ALINEAMIENTO
        'AL_EJE1_DESVIACION', 'AL_EJE1_RESULTADO',
        'AL_EJE2_DESVIACION', 'AL_EJE2_RESULTADO',
        'AL_EJE3_DESVIACION', 'AL_EJE3_RESULTADO',
        'AL_EJE4_DESVIACION', 'AL_EJE4_RESULTADO',
        'AL_EJE5_DESVIACION', 'AL_EJE5_RESULTADO',
        // NEUMÁTICOS
        'NEU_EJE1_MEDIDA_DER', 'NEU_EJE1_MEDIDA_IZQ', 'NEU_EJE1_RESULTADO',
        'NEU_EJE2_MEDIDA_DER', 'NEU_EJE2_MEDIDA_IZQ', 'NEU_EJE2_RESULTADO',
        'NEU_EJE3_MEDIDA_DER', 'NEU_EJE3_MEDIDA_IZQ', 'NEU_EJE3_RESULTADO',
        'NEU_EJE4_MEDIDA_DER', 'NEU_EJE4_MEDIDA_IZQ', 'NEU_EJE4_RESULTADO',
        'NEU_EJE5_MEDIDA_DER', 'NEU_EJE5_MEDIDA_IZQ', 'NEU_EJE5_RESULTADO',
        // LUCES
        'LUZ_BAJA_DER', 'LUZ_BAJA_IZQ', 'LUZ_BAJA_ALINEAMIENTO', 'LUZ_BAJA_RESULTADO',
        'LUZ_ALTA_DER', 'LUZ_ALTA_IZQ', 'LUZ_ALTA_ALINEAMIENTO', 'LUZ_ALTA_RESULTADO',
        'LUZ_ADICIONAL_DER', 'LUZ_ADICIONAL_IZQ', 'LUZ_ADICIONAL_ALINEAMIENTO', 'LUZ_ADICIONAL_RESULTADO',
        'LUZ_NEBLINEROS_DER', 'LUZ_NEBLINEROS_IZQ', 'LUZ_NEBLINEROS_ALINEAMIENTO', 'LUZ_NEBLINEROS_RESULTADO',
        // SUSPENSIÓN
        'SUSP_DELANTERA_IZQ', 'SUSP_DELANTERA_DER', 'SUSP_DELANTERA_DESV', 'SUSP_DELANTERA_RESULTADO',
        'SUSP_POSTERIOR_IZQ', 'SUSP_POSTERIOR_DER', 'SUSP_POSTERIOR_DESV', 'SUSP_POSTERIOR_RESULTADO',
        'SUSP_RESULTADO_FINAL',
        // EMISIONES
        'EMIS_TEMP_ACEITE', 'EMIS_RPM', 'EMIS_OPACIDAD',
        'EMIS_TEMP_ACEITE_DER', 'EMIS_RPM_DER', 'EMIS_OPACIDAD_DER',
        'EMIS_CO_RALENTI', 'EMIS_CO_ACELERACION',
        'EMIS_CO2_RALENTI', 'EMIS_CO2_ACELERACION',
        'EMIS_HC_RALENTI', 'EMIS_HC_ACELERACION',
        'EMIS_RESULTADO',
        // SONORAS
        'EMIS_SONORA_DB', 'EMIS_SONORA_RESULTADO',
        // GLOBAL
        'RESULTADO_GLOBAL', 'OBSERVACIONES'
    ];

}
